### ISSUE TITLE
writing our own code of conduct

### ISSUE THREAD

**Issue by tolry** [simpspector/simpspector#106]
Having a code of conduct at all is a nice start, but since we are currently not 100% satisfied, we should probably phrase our own version.

If no one objects, I would take up the task. @simplethings/simpspector

**Comment by larsborn** [comment]
no objections from my side!

**Comment by tolry** [comment]
Unfortunately I did not have any spare time to work on this and might get around to working on this for some time.

How about updating to the updated version. As far as I can see lots of improvements were made http://contributor-covenant.org/version/1/2/0/code_of_conduct.md

**Comment by larsborn** [comment]
jep, looks somehow better.
