### ISSUE TITLE
How to manage documentation

### ISSUE THREAD

**Issue by tolry** [simpspector/simpspector#109]
Open discussion:

* where do we put documentation: simplethings/SimpSpector, simplethings/simpspector-analyzer, both or a separate repo?
* should we stick to markdown and simply keep linking within the github explorer or switch to somerthing more sophisticated like github pages?

@simplethings/simpspector

**Comment by tolry** [comment]
my two cents:

* I like having all the documentation in one place and link to it from all repository readmes
* github pages seems like a good idea to me, does anyone already have experience or does care to do some investigations?
* github pages would probably mean separate repo, right?
* will github pages/separate repo make it harder for us to "force" people to update the docs when contributing new stuff?

**Comment by tolry** [comment]
I've found these instructions on how to use github pages with sculpin, might be worth a look. No guarantees though that this is still up to date. https://gist.github.com/mrkrstphr/2e79e55229b2ef7a343a

**Comment by tolry** [comment]
I have been prototyping a simple documentation template with bootstrap and sculpin, so if anyone else wants to work on this, we should probably work beforehand to avoid overlap.

**Comment by tolry** [comment]
I have pushed a prototype to https://github.com/simplethings/simpspector-docs and appreciate any suggestions, criticism, ...

It really is just a starting point. I think uploading the code makes it the best way to discuss this. So, any feedback welcome.

**Comment by larsborn** [comment]
I think we discussed this in person and agreed, that the github page is awesome. So what's left to do here? Or can we close it?

**Comment by tolry** [comment]
Agreed, more general discussions might be part of the hack day.
