### ISSUE TITLE
Introduce our new awesome logo

### ISSUE THREAD

**Issue by tolry** [simpspector/simpspector#110]
It's owl gonna change! Sophie has worked on a logo for SimpSpector, given @DavidBadura's idea of having an owl as a mascott.

Although losing a bit of our inspector gadget identity, we had decided using the gadget, since every project needs an animal mascott and the artwork is really great. So, let's use it, shall we?

Todos I see here are:

* integrate in README.md / documentation (as soon as we have one)
* integrate in layout: maybe the large version only on the dashboard and perhaps a small one in the menu bar?

**Comment by larsborn** [comment]
+1 for the owl. And thanks for the great pun. 

I think your suggestions are a good start. We'll feel , where to put the owl, when the time comes.

**Comment by tolry** [comment]
Close this issue, create more concrete ones?
