### ISSUE TITLE
var/checkouts garbage collector

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/simpspector#121]
there is some collected on if the process is aborted.

On the test system we had ~1 GB

**Comment by tolry** [comment]
Is there reason for keeping this data at all after a commit is processed, i.e. do we reuse checkouts in any way right? If not, I would suggest, that the process generating the checkout should be responsible for cleanup afterwards.

In case of an error we might still be left with orphaned data, so a garbage collector might still be good idea.

**Comment by DavidBadura** [comment]
> that the process generating the checkout should be responsible for cleanup afterwards.

which is already done :-) 
https://github.com/simpspector/simpspector/blob/master/src/SimpleThings/AppBundle/WorkspaceManager.php#L62

> In case of an error we might still be left with orphaned data, so a garbage collector might still be good idea.

Yes, precisely in this case should the garbage collector to clean up the workspace.

**Comment by tolry** [comment]
OK, so this is just a failsafe, if the cronjob got interrupted unexpectedly. Hmmm, shouldn't, hopefully, happen that often.

**Comment by DavidBadura** [comment]
shouldn't... but as a precaution we need a wall-e :wink:

**Comment by tolry** [comment]
careful, Disney's lawyers are everywhere :wink:
