### ISSUE TITLE
PR/MR webhooks doesn't work anymore

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/simpspector#128]

**Comment by tolry** [comment]
That's quite general:

* do they fail in any case?
* do you get an error message?
* do you perhaps already know the cause for this?

**Comment by DavidBadura** [comment]
* i don't know
* i don't know
* no

**Comment by tolry** [comment]
Ok, so currently there is only a symptom, which would be: you are pushing to an MR and no entry is created in the simpspector DB?

**Comment by DavidBadura** [comment]
correct :-)

**Comment by DavidBadura** [comment]
ref #130
