### ISSUE TITLE
Ciconia (markdown) seems to be dead/unmantained

### ISSUE THREAD

**Issue by smoench** [simpspector/simpspector#170]
Should we fork it or replace it with an other libary?
If we still keep using Ciconia we can't upgrade to symfony 3 (#119) because of some behavior/deprecations changes on symfony/options-resolver. https://github.com/kzykhys/Ciconia/blob/1.0/composer.json#L20

```
Calling the Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead. (1458 times) 
```

@tolry @larsborn @dragonito @DavidBadura

**Comment by tolry** [comment]
I would vote strongly to switch libraries. Maintaining the fork of such a large code base wouldn't do us any good, imo. Anybody got some spare time to test out a few candidates, first coming to mind being

* https://github.com/thephpleague/commonmark
* https://github.com/fluxbb/commonmark (fork from Ciconia)

Fluxbb might be an easy target. Migration should be easy if not too much of the structure has been refactored from ciconia.

**Comment by larsborn** [comment]
https://github.com/fluxbb/commonmark/issues/7 looks not so good :-)

**Comment by tolry** [comment]
If it comes to being future proof, php-league is probably the safest bet - packagist statistics also are quite clear on community favorite  https://packagist.org/packages/league/commonmark

**Comment by DavidBadura** [comment]
:+1: for thephpleague/commonmark

**Comment by tolry** [comment]
Any volunteers?

**Comment by smoench** [comment]
I will give it a try

**Comment by tolry** [comment]
great
