### ISSUE TITLE
split SimpSpector in two projects

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/simpspector#44]
I think it is nice to split SimpSpector in two projects. In an analysis tool like `SimpSpector-CLI` and a web interface. The advantage is that the cli tool has all the dependencies to the other tools and you can write easier tests.

**Comment by smoench** [comment]
I think it would be a good start if all simpspector (cli/common) related things would be moved to an other namespace, but still keeping them in this repository.

**Comment by tolry** [comment]
I guess we can close this now? :smile:
