### ISSUE TITLE
continous integration

### ISSUE THREAD

**Issue by tolry** [simpspector/simpspector#96]
As discussed in today's coding dojo: installation is currently quite agonizing
- installing / configuring npm, bower, gulp
- building assets
- installing/updating composer dependencies
- cache:clear, db-migrations, ...

This should all be done by travis, packaged (debian, tgz, ...). Possibly some builds should create releases on github (only tags?).

**Comment by DavidBadura** [comment]
ref #116 & https://github.com/simpspector/simpspector/blob/master/bin/update

**Comment by larsborn** [comment]
so #116 is merged. Whats the next step here? Isn't travis for testing? And are we going to use it for packaging?

**Comment by tolry** [comment]
* Has anybody experience using travis for packaging?
* Is these even currently possible?
* How can we publish a generated package as release, including the tarball ...

**Comment by tolry** [comment]
So I guess, research on this might be a good next step?

**Comment by larsborn** [comment]
covered by #196 .
