### ISSUE TITLE
DX

### ISSUE THREAD

**Issue by larsborn** [simpspector/simpspector#97]
our DX is *very* bad. What should we do?

**Comment by larsborn** [comment]
Elaboration:

* setting up a dev env is a pain (on windows *and* linux)
* keeping it up to date and running is a pain too
* this makes it nearly impossible for new people, to join with (for example easypicks) because the setup is the hardest part.

We should discuss a solution very soon! Maybe tomorrow at lunch?

**Comment by tolry** [comment]
:+1: 

my ideas on this

* imho the hard parts are
   * get gitlab running (in docker or anywhere)
   * get npm/gulp setup properly
* gitlab
   * if we had github integration, most people could simply have a github test-repo to test those things
   * also with sufficient fixture data, lots of changes can be made and tested without gitlab/github
* npm/gulp
   * somebody would have to work on better understanding npm/gulp (why do we need install gulp globally + locally?) - I would volunteer for this
   * we need to do some automation on this part for #96 already *buzzword* **synergy** - so, we should build a script that can be used by travis as well as developers to setup their installation

**Comment by larsborn** [comment]
as a documentation of our talk today: I'm totally with you. 
* @smoench volunteered (?) for the github integration
* afair @tolry wanted to get a better understanding of npm/gulp/bower 
* and I will create some fixtures (for people who only want to work on the interface)

**Comment by larsborn** [comment]
#99

**Comment by tolry** [comment]
:+1:

**Comment by larsborn** [comment]
I added some lines to the `development-environment.md`. It's still not a good DX, I'll look into it after I finished the fixtures branch.

**Comment by tolry** [comment]
Sounds a bit like the node version of https://rvm.io/ - I'll check it out, thx.

**Comment by larsborn** [comment]
I think we moved everything from this issue to smaller ones, right?

also splitting up SimpSpector and analyzer was a very good idea.

**Comment by tolry** [comment]
Agreed, this was more or less a brainstorming issue. Can be closed, right?

**Comment by DavidBadura** [comment]
ref #131

**Comment by tolry** [comment]
:+1: for closing this issue - I think every concern raised here was either fixed or has an issue tagged as DX by now
