### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by larsborn** [simpspector/simpspector#99]
DX issue: make it very easy, to enhance the frontend.

**Comment by tolry** [comment]
also for gadget development you won't need github/gitlab either (see tests for blacklist function or comment gadget )

**Comment by larsborn** [comment]
at the moment, the gitlab config parameters are mandatory. Didn't have time to look into it.

**Comment by larsborn** [comment]
@tolry in theory, tests suffice but it might be kind of hard to implement a gadget without the big picture. Or am I misunderstanding you?

**Comment by tolry** [comment]
Sure, one needs to do some integration testing at the end, e.g. to realize you forgot to register the service and the gadget isn't used at all :smile:. But most gadgets are just working on some files and don't need the big gitlab-gulp-bower-setup at all. The workspace object is very easily instantiated and everything you need to run/test your gadget.

It was just a side note to this issue anyway, kind of a reminder to myself that I wanted to open an issue on DX to compile a special documentation file on how to implement a new gadget. My guess is, that this is a very good point for other developers to start contributing. Any thoughts on that?

**Comment by larsborn** [comment]
@tolry this is totally true. So, you open up the issue and feel responsible for this?

**Comment by tolry** [comment]
done

**Comment by larsborn** [comment]
close here?

**Comment by dragonito** [comment]
+1

**Comment by tolry** [comment]
:+1:
